# Generated by Django 4.2.1 on 2023-05-31 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reference',
            new_name='AssignedArea',
        ),
    ]
