# Generated by Django 4.2.1 on 2023-10-04 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_useraccountmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minutes', models.IntegerField(default=30)),
                ('seconds', models.IntegerField(default=0)),
                ('session_ended', models.BooleanField(default=False)),
                ('user_id', models.IntegerField()),
            ],
        ),
    ]
