# Generated by Django 4.2.1 on 2023-10-04 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_usertimer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserTimer',
            new_name='Timer',
        ),
    ]
