# Generated by Django 4.2.1 on 2023-10-04 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_timer'),
        ('polls', '0005_rename_usertimer_timer'),
    ]

    operations = [
    ]
