# Generated by Django 4.2.1 on 2023-10-04 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_merge_0004_timer_0005_rename_usertimer_timer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timer',
            name='id',
        ),
        migrations.AlterField(
            model_name='timer',
            name='user_id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
