# Generated by Django 4.2.1 on 2023-10-10 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_remove_timer_id_alter_timer_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeatingCapacity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_id', models.CharField(max_length=10)),
                ('total_seats', models.PositiveIntegerField()),
                ('occupied_seats', models.PositiveIntegerField()),
            ],
        ),
    ]
