# Generated by Django 4.2.1 on 2023-10-10 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_seatingcapacity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SeatingCapacity',
        ),
    ]
