# Generated by Django 4.2.1 on 2023-10-17 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_alter_timer_minutes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timer',
            name='minutes',
            field=models.IntegerField(default=30),
        ),
    ]
