# Generated by Django 4.1 on 2023-05-26 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='WalkinBooking',
            fields=[
                ('bookingid', models.AutoField(primary_key=True, serialize=False)),
                ('referenceid', models.CharField(max_length=20)),
                ('userid', models.CharField(max_length=20)),
                ('schedule', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
            ],
        ),
    ]
