# Generated by Django 4.1 on 2023-05-27 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiladmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('logid', models.AutoField(primary_key=True, serialize=False)),
                ('referenceid', models.CharField(max_length=20)),
                ('userid', models.CharField(max_length=20)),
                ('date', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
            ],
        ),
    ]
