# Generated by Django 4.1 on 2023-05-27 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiladmin', '0002_logs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logs',
            old_name='date',
            new_name='datetime',
        ),
    ]
