# Generated by Django 4.1 on 2023-05-30 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiladmin', '0003_rename_date_logs_datetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.RenameModel(
            old_name='Logs',
            new_name='AdminReportLogs',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
