# Generated by Django 4.2.1 on 2023-06-01 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiladmin', '0004_adminaccount_rename_logs_adminreportlogs_delete_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AdminAccount',
            new_name='AdminAccountModel',
        ),
        migrations.RenameModel(
            old_name='AdminReportLogs',
            new_name='AdminReportLogsModel',
        ),
        migrations.RenameModel(
            old_name='WalkinBooking',
            new_name='WalkinBookingModel',
        ),
    ]
